language: objective-c
os: osx
osx_image: xcode11.3   
jobs:
  include:
  - script:
    - travis_wait make production
env:
  global:
    - tag=1.0.3
branches:
  only:
  - master
before_script:
- brew tap tcnksm/ghr
- brew install ghr
script:
- make production
after_success:
  - ./push.sh
  - ghr -t $TOKEN -u ppm-manish -r mnzz-ios -c master -b "Mnzz SDK version $tag" $tag releases/